### ISSUE TITLE
maybe exits thread-safe problem?

### ISSUE THREAD

**Issue by youw3** [bkiers/tiny-language-antlr4#11]
i run multi-thread program, i found when i use user-defined-function like

def fun():
   ...
   return a

b = fun()

i found, for example  thread A result will return to Thread B

i print the result in udf  before return statement, its ok, but after return ,the result went wrong.

i suspect the ReturnValue has a thread-safety problem
please mention it, thank you!

**Comment by youw3** [comment]
@bkiers

**Comment by bkiers** [comment]
Hi @youw3, thanks, but for such an obvious toy language, I don't see the need to put a lot caveats in the README.

**Comment by youw3** [comment]
i am newbie in Antlr4,  thank you for your  project!  it helps me a lot !  can you give me some advice to prevent thread-safety problems or any improvement for designing " return " statement

**Comment by bkiers** [comment]
Hey @youw3, for someone to be able to help you, they'd need to be able to reproduce the issue you're having. So if you create a small app that demonstrates your problem, I suggest you post that on [stackoverflow](https://stackoverflow.com/). Good luck!
