### ISSUE TITLE
TLBaseVisitor Class Missing

### ISSUE THREAD

**Issue by NovaMachina** [bkiers/tiny-language-antlr4#2]
EvalVisitor and SymbolVisitor extend this class, however it does not exist in the project.

**Comment by bkiers** [comment]
Hi, that file is, like the lexer and parser files, a generated source file. They are purposely left out of source control and will be generated when running `mvn antlr4:antlr4` (as mentioned in the README).

**Comment by filipevarjao** [comment]
@bkiers I did each step described in the README but still without TLBaseVisitor class.

**Comment by bkiers** [comment]
@Filipergv did you look in `target/generated-sources/` after doing `mvn antlr4:antlr4`?

**Comment by filipevarjao** [comment]
You are right, thank you for all support.

**Comment by bkiers** [comment]
No problem @Filipergv
