### ISSUE TITLE
custom macro

### ISSUE THREAD

**Issue by LiQingMuBai** [bkiers/tiny-language-antlr4#3]
actually,i want to have use-define macro such as like VDL.

**Comment by bkiers** [comment]
I won't be extending _Tiny Language_ with more constructs/features (it wouldn't be "tiny" if I start doing that :)).

Feel free to fork this project and try to implement this feature yourself. If you get stuck, you can always ask for help on [stackoverflow](http://stackoverflow.com/questions/tagged/antlr) or some other public forum or mailing list.

Good luck!
