### ISSUE TITLE
your blog post about Tiny Language cannot be reached

### ISSUE THREAD

**Issue by tinymindxx** [bkiers/tiny-language-antlr4#8]
hi,thanks for your amazing work. 

The blog you mentioned in the README.md cannot be reached any more. do you have  a backup address and update it ?

thanks again.

**Comment by bkiers** [comment]
Hi @frozenxia, the blog itself is not online anymore, but in the README the link to it points to an arcive.org url, which is still online: [web.archive.org/web/20140519034030/http://bkiers.blogspot.nl/2011/03/creating-your-own-programming-language.html](http://web.archive.org/web/20140519034030/http://bkiers.blogspot.nl/2011/03/creating-your-own-programming-language.html)

If that link does not work with you, I suspect you can't reach [web.archive.org](https://web.archive.org) from your location.
